### ISSUE TITLE
Need to enforce ligand names, or auto-assign 

### ISSUE THREAD

**Issue by JenkeScheen** [openforcefield/alchemiscale#225] opened 2024-01-10 10:42 UTC
When a network is submitted with no names assigned to ligands, this is currently carried through `alchemiscale` without failing. This means that nodes are assigned an empty string as node name, and pulling in results returns:
```
dict_items([('-', [TransformationResult(type='TransformationResult', ligand_a='', ligand_b='', phase='complex', estimate=<Quantity(-25.4637053, 'kilocalorie / mole')>, uncertainty=<Quantity(0.0976474617, 'kilocalorie / mole')>), TransformationResult(type='TransformationResult', ligand_a='', ligand_b='', phase='complex', estimate=<Quantity(-0.803647029, 'kilocalorie / mole')>, uncertainty=<Quantity(0.300722729, 'kilocalorie / mole')>), [..]
```
which is difficult/impossible to parse as there is no way to compare edges to each other.

Solutions would be to A) enforce the user to set ligand names, or B) to auto-assign random strings as ligand names.

**Comment by IAlibay** [comment] 2024-01-10 11:22
Tagging @dwhswenson here since this looks like more of a gufe question.

These objects have a unique key which can / should be used instead of the name string for comparison. As far as I remember, it's a specific design decision that names shouldn't be enforced here.

**Comment by dwhswenson** [comment] 2024-01-10 12:38
As @IAlibay mentions, all `GufeTokenizable`s (base class for most objects, including all `Component`s, `Transformation`s, etc) carry a `.key` attribute. The key is a unique and reproducible hash for the object, and should meet your needs, @JenkeScheen. Treat this as a backup to the name (or really, use the `.key` for anything that doesn't need to be user-facing; the name is only a convenience for user interaction.)

Importantly, for objects used in setting up a simulation, this is **not** a random string (although it looks random to the user). If you create the same object twice, even in different hardware environments or with different software versions (within a major release cycle), it should create the same `.key`. Result objects are the exception: for result objects, the `key` is a UUID (random string) set on creation -- we decided that the cost/benefit of hashing a full set of results to obtain a reproducible key made UUIDs better.

Details on the GUFE key at: https://gufe.readthedocs.io/en/latest/guide/serialization.html#understanding-the-theory-the-gufe-key

**Comment by dotsdl** [comment] 2024-01-10 16:18
@JenkeScheen `alchemiscale` and `gufe` do not depend on ligand names for any functionality; as @dwhswenson and @IAlibay have said, all `GufeTokenizable`s feature a unique `key`, and this is what is used to differentiate them in both `gufe` and `alchemiscale`.

How are you pulling in results as above? Is ligand name-based result assembly being done in the `asapdiscovery-alchemy` application layer?

**Comment by dotsdl** [comment] 2024-02-23 03:26
This has been addressed in `asapdiscovery-alchemy` here: https://github.com/choderalab/asapdiscovery/issues/727

Closing!

**Closed by dotsdl** 2024-02-23 03:26 UTC
